#!/bin/bash

mydir="${0%/*}"
set -e


if [[ ! -d "$mydir/src/node_modules" ]]; then
	echo 'Installing script dependencies...'
	(cd $mydir/src; npm install)
fi

(cd $mydir; src/node_modules/.bin/ts-node --project src/tsconfig.json src/index.ts $*)
